"""
Context Runtime Models

Core data models for Context Intelligence runtime.

S4 Context Intelligence
"""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class ContextLifecycle(str, Enum):
    """
    Context lifecycle states.
    """

    CREATED = "created"
    ACTIVE = "active"
    STALE = "stale"
    ARCHIVED = "archived"
    REMOVED = "removed"


class ContextAllocation(BaseModel):
    """
    Token allocation policy for context budget.
    """

    system: int = 0
    memory: int = 0
    knowledge: int = 0
    conversation: int = 0


class ContextBudget(BaseModel):
    """
    Token budget tracking model.

    Tracks:
    - maximum allowed tokens
    - allocation
    - consumed tokens
    - reserved tokens
    """

    max_tokens: int

    allocation: ContextAllocation

    consumed_tokens: int = 0

    reserved_tokens: int = 0

    @property
    def used_tokens(self) -> int:
        """
        Backward compatible accessor.
        """

        return self.consumed_tokens

    @property
    def remaining_tokens(self) -> int:
        """
        Remaining available tokens.
        """

        return (
            self.max_tokens
            - self.consumed_tokens
            - self.reserved_tokens
        )


class ContextRuntimeState(BaseModel):
    """
    Runtime state for active context.

    Represents the context lifecycle object
    managed by ContextRuntimeCoordinator.
    """

    context_id: str

    lifecycle: ContextLifecycle = (
        ContextLifecycle.CREATED
    )

    budget: ContextBudget

    created_at: datetime = Field(
        default_factory=datetime.utcnow
    )

    updated_at: datetime = Field(
        default_factory=datetime.utcnow
    )

    metadata: dict[str, object] = Field(
        default_factory=dict
    )


class ContextCandidate(BaseModel):
    """
    Candidate context returned from retrieval pipeline.

    Used by:
    - Context Retriever
    - Context Ranker
    - Context Selector

    A candidate represents a retrievable
    context unit before final selection.
    """

    context_id: str

    """
    Raw context content.

    Used by:
    - ranking algorithms
    - semantic scoring
    - context assembly
    """

    content: str | None = None

    """
    Ranking score generated by ranker.
    """

    score: float = 0.0

    """
    Lifecycle state of the context.
    """

    lifecycle: ContextLifecycle

    """
    Runtime budget snapshot.
    """

    budget: ContextBudget | None = None

    """
    Additional retrieval metadata.
    """

    metadata: dict[str, object] = Field(
        default_factory=dict
    )


class SelectedContext(BaseModel):
    """
    Final context package produced by Context Selector.

    Represents the context payload that will be
    passed into Agent Runtime.

    Created by:
        Context Selector

    Consumed by:
        Agent Runtime
    """

    items: list[ContextCandidate] = Field(
        default_factory=list
    )

    total_tokens: int = 0

    total_score: float = 0.0

    metadata: dict[str, object] = Field(
        default_factory=dict
    )
