"""
Context Selection Pipeline Integration Tests

Sprint:
    S4-007-003 Context Selector

Pipeline:

Context Candidates
        |
        v
DefaultContextRanker
        |
        v
Ranked Context Candidates
        |
        v
DefaultContextSelector
        |
        v
SelectedContext
"""

from app.context_runtime.models import (
    ContextCandidate,
    ContextLifecycle,
)

from app.context_runtime.policies import (
    SelectionPolicy,
)

from app.context_runtime.ranker import (
    DefaultContextRanker,
)

from app.context_runtime.selector import (
    DefaultContextSelector,
)


def create_candidate(
    context_id: str,
    content: str,
) -> ContextCandidate:
    """
    Create runtime context candidate.
    """

    return ContextCandidate(
        context_id=context_id,
        content=content,
        lifecycle=ContextLifecycle.ACTIVE,
        metadata={
            "source": "test"
        },
    )


def test_ranker_to_selector_pipeline():
    """
    Ranked candidates should flow into selector
    and produce final SelectedContext.
    """

    candidates = [
        create_candidate(
            "context-a",
            "important memory about project",
        ),
        create_candidate(
            "context-b",
            "related memory information",
        ),
        create_candidate(
            "context-c",
            "unrelated content",
        ),
    ]

    ranker = DefaultContextRanker()

    ranked_candidates = ranker.rank(
        candidates,
        query="memory",
    )

    selector = DefaultContextSelector()

    selected = selector.select(
        ranked_candidates,
        SelectionPolicy(
            min_score=0.0,
            max_items=10,
            max_tokens=1000,
        ),
    )

    assert len(selected.items) > 0

    assert (
        selected.metadata["selector"]
        == "default"
    )


def test_pipeline_respects_selection_budget():
    """
    Pipeline should stop selecting when
    token budget is reached.
    """

    candidates = [
        create_candidate(
            "large-a",
            "a" * 100,
        ),
        create_candidate(
            "large-b",
            "b" * 100,
        ),
    ]

    ranker = DefaultContextRanker()

    ranked_candidates = ranker.rank(
        candidates,
        query="large",
    )

    selector = DefaultContextSelector()

    selected = selector.select(
        ranked_candidates,
        SelectionPolicy(
            min_score=0.0,
            max_items=10,
            max_tokens=30,
        ),
    )

    assert len(selected.items) == 1


def test_pipeline_preserves_rank_priority():
    """
    Selector should preserve the ordering
    generated by Context Ranker.
    """

    candidates = [
        create_candidate(
            "highest",
            "top priority memory",
        ),
        create_candidate(
            "middle",
            "medium relevance memory",
        ),
        create_candidate(
            "lowest",
            "low relevance memory",
        ),
    ]

    ranker = DefaultContextRanker()

    ranked_candidates = ranker.rank(
        candidates,
        query="priority memory",
    )

    selector = DefaultContextSelector()

    selected = selector.select(
        ranked_candidates,
        SelectionPolicy(
            min_score=0.0,
            max_items=3,
            max_tokens=1000,
        ),
    )

    ranked_ids = [
        item.context_id
        for item in ranked_candidates
    ]

    selected_ids = [
        item.context_id
        for item in selected.items
    ]

    assert selected_ids == ranked_ids


def test_pipeline_returns_context_package():
    """
    Pipeline output should be SelectedContext.
    """

    candidates = [
        create_candidate(
            "memory-1",
            "user preference memory",
        )
    ]

    ranker = DefaultContextRanker()

    ranked_candidates = ranker.rank(
        candidates,
        query="preference",
    )

    selector = DefaultContextSelector()

    selected = selector.select(
        ranked_candidates,
        SelectionPolicy(
            min_score=0.0,
            max_items=5,
            max_tokens=1000,
        ),
    )

    assert len(selected.items) == 1

    assert (
        selected.items[0].context_id
        == "memory-1"
    )

    assert (
        selected.total_tokens
        > 0
    )

    assert (
        selected.metadata["selector"]
        == "default"
    )
